version: '4.0'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/based-agent-test:latest@sha256:20185547e526b6b49a7434507ecb5ad9ebb4e333c4fb8a6d3c059eb8157c522e
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
