version: '4.0'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: prod
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/based-agent-test:latest@sha256:c4e0c505004bfd36cfc596efe652d8e1991e744a04251315a842ca9ca19c318f
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
