services:
    web:
        environment:
            BASE_API_KEY: ${BASE_API_KEY}
            TWITTER_CLIENT_KEY: ${TWITTER_CLIENT_KEY}
            TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
            TWITTER_REFRESH_TOKEN: ${TWITTER_REFRESH_TOKEN}
            TWITTER_LAST_TIMESTAMP: ${TWITTER_LAST_TIMESTAMP}
            TWITTER_API_KEY: ${TWITTER_API_KEY}
            TWITTER_API_SECRET: ${TWITTER_API_SECRET}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            MPC_PUBLIC_KEY_TESTNET: ${MPC_PUBLIC_KEY_TESTNET}
            MPC_PUBLIC_KEY_MAINNET: ${MPC_PUBLIC_KEY_MAINNET}
        platform: linux/amd64 # Explicitly set for TDX
        image: mattdlockyer/shade-agent-basednames:latest@sha256:aea797b3988f31aa369efc51eedb878a3b62b4aa2c3099aa06e615fc6fcaf6ca
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
